function [Date, Vec] = DataReader(filename)
fileID = fopen(filename);
Data = textscan(fileID,'%*f %*c.%*c. %{yyyy-MMM-dd HH:mm:ss.SSSS}D %f %f %f %f %f %f','Delimiter',',','HeaderLines',23);
Date = Data{1};
X = Data{2};
Y = Data{3};
Z = Data{4};
VX = Data{5};
VY = Data{6};
VZ = Data{7};
Vec = [X,Y,Z,VX,VY,VZ];